#!/usr/bin/env bash
# Generate firmware/garden-node/arduino_secrets.h from .env (the single source
# of truth). Both files are gitignored. Run after editing .env, before
# compiling/uploading the sketch.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"
OUT="$ROOT/firmware/garden-node/arduino_secrets.h"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "error: $ENV_FILE not found. Copy .env.example to .env and fill it in." >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a; source "$ENV_FILE"; set +a

: "${WIFI_SSID:?set WIFI_SSID in .env}"
: "${WIFI_PASS:?set WIFI_PASS in .env}"
: "${OAUTH_CLIENT_ID:?set OAUTH_CLIENT_ID in .env}"
: "${OAUTH_CLIENT_SECRET:?set OAUTH_CLIENT_SECRET in .env}"

cat > "$OUT" <<EOF
// AUTO-GENERATED by scripts/gen-arduino-secrets.sh from .env — do not edit by
// hand, and never commit (gitignored). Re-run the script after changing .env.
#pragma once

#define SECRET_WIFI_SSID "${WIFI_SSID}"
#define SECRET_WIFI_PASS "${WIFI_PASS}"

#define SECRET_OAUTH_CLIENT_ID     "${OAUTH_CLIENT_ID}"
#define SECRET_OAUTH_CLIENT_SECRET "${OAUTH_CLIENT_SECRET}"
EOF

echo "wrote $OUT (client_id=${OAUTH_CLIENT_ID}, secret=***${OAUTH_CLIENT_SECRET: -4})"
